---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах  
implicit:
  - В катологе должно отображаться постранично по 30 товаров
  - Если товаров меньше 30, кнопки переключения страниц должны быть скрыты
  - Фильтрация товаров должна происходить по бренду, наличию и цене
  - В фильтре цены вводимые числа не могут быть отрицательными
  - Пользователь должен иметь возможность добавить несколько единиц одного товара в корзину
  - Пользователь должен иметь возможность удалить позицию или единицу товара из корзины
  - Пользователь должен иметь возможность очистить корзину
  - Пользователь должен иметь возможность оформить заказ
  - После оформления заказа корзина должна очищаться
  - Список товаров в корзине должен храниться в сессии браузера
  - Сайт должен иметь английскую и русскую версии
  - Сайт должен иметь адаптивную верстку
  - Сайт должен быть реализован как SPA-приложение
